//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orubase.Native.WindowsPhone {
    using System;
    using System.Windows;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrubaseErrorsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public OrubaseErrorsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var assembly = Application.Current.GetType().Assembly;
                    var ast = assembly.FullName;
                    char[] delimit = new char[] { ',' };
                    string[] parts = ast.Split(delimit);
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(parts[0]+".Resources.OrubaseErrorsStrings", typeof(OrubaseErrorsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 4 AppBarItem cannot be added.
        /// </summary>
        public static string AppBarItemCountExceededError {
            get {
                return ResourceManager.GetString("AppBarItemCountExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBar having Zero Items.
        /// </summary>
        public static string AppBarItemCountZeroError {
            get {
                return ResourceManager.GetString("AppBarItemCountZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such AppBarItem found.
        /// </summary>
        public static string AppBarItemNotFoundError {
            get {
                return ResourceManager.GetString("AppBarItemNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 4 AppBarMenuItem cannot be added.
        /// </summary>
        public static string AppBarMenuItemCountExceededError {
            get {
                return ResourceManager.GetString("AppBarMenuItemCountExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBar having Zero MenuItems.
        /// </summary>
        public static string AppBarMenuItemCountZeroError {
            get {
                return ResourceManager.GetString("AppBarMenuItemCountZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such AppBarMenuItem found.
        /// </summary>
        public static string AppBarMenuItemNotFoundError {
            get {
                return ResourceManager.GetString("AppBarMenuItemNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio not recorded.
        /// </summary>
        public static string AudioNotRecordedError {
            get {
                return ResourceManager.GetString("AudioNotRecordedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call ShowAppbar.
        /// </summary>
        public static string CallShowAppBar {
            get {
                return ResourceManager.GetString("CallShowAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not supported.
        /// </summary>
        public static string CameraNotSupportedError {
            get {
                return ResourceManager.GetString("CameraNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ID_CAP_CONTACTS capabilities in manifest file.
        /// </summary>
        public static string ContactsCapabilitiesNotEnabledError {
            get {
                return ResourceManager.GetString("ContactsCapabilitiesNotEnabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key does not exist.
        /// </summary>
        public static string DictionaryKeyNotExistsError {
            get {
                return ResourceManager.GetString("DictionaryKeyNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found.
        /// </summary>
        public static string DictionaryNoItemFoundError {
            get {
                return ResourceManager.GetString("DictionaryNoItemFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Already Exists.
        /// </summary>
        public static string DirectoryAlreadyExistsError {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Creation Failure.
        /// </summary>
        public static string DirectoryCreationFailedError {
            get {
                return ResourceManager.GetString("DirectoryCreationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Deletion Failure.
        /// </summary>
        public static string DirectoryDeletionFailureError {
            get {
                return ResourceManager.GetString("DirectoryDeletionFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Exists.
        /// </summary>
        public static string DirectoryNotExistsError {
            get {
                return ResourceManager.GetString("DirectoryNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to Add New Contact.
        /// </summary>
        public static string FailureToAddContactError {
            get {
                return ResourceManager.GetString("FailureToAddContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Exists.
        /// </summary>
        public static string FileAlreadyExistsError {
            get {
                return ResourceManager.GetString("FileAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Creation Failure.
        /// </summary>
        public static string FileCreationFailureError {
            get {
                return ResourceManager.GetString("FileCreationFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Deletion Error.
        /// </summary>
        public static string FileDeletionError {
            get {
                return ResourceManager.GetString("FileDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not Exists.
        /// </summary>
        public static string FileNotExistsError {
            get {
                return ResourceManager.GetString("FileNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera not supported.
        /// </summary>
        public static string FrontCameraNotSupportedError {
            get {
                return ResourceManager.GetString("FrontCameraNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Map and Location capabilities in Manifest file.
        /// </summary>
        public static string MapAndLocationCapabilitiesNotEnabledError {
            get {
                return ResourceManager.GetString("MapAndLocationCapabilitiesNotEnabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        //public static string OrubaseErrorsStrings {
        //    get {
        //        return ResourceManager.GetString("OrubaseErrorsStrings", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.18033
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace DemoApp.Resources {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-typ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrubaseErrorsStrings_Designer {
            get {
                return ResourceManager.GetString("OrubaseErrorsStrings_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature not captured.
        /// </summary>
        public static string SignatureNotCapturedError {
            get {
                return ResourceManager.GetString("SignatureNotCapturedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video not recorded.
        /// </summary>
        public static string VideoNotRecordedError {
            get {
                return ResourceManager.GetString("VideoNotRecordedError", resourceCulture);
            }
        }
    }
}
