//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orubase.Native.WindowsPhone {
    using System;
    using System.Windows;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrubaseSuccessResultsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public OrubaseSuccessResultsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var assembly = Application.Current.GetType().Assembly;
                    var ast = assembly.FullName;
                    char[] delimit = new char[] { ',' };
                    string[] parts = ast.Split(delimit);
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(parts[0]+".Resources.OrubaseSuccessResultsStrings", typeof(OrubaseSuccessResultsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBar Successfully Created.
        /// </summary>
        public static string AppBarCreationSuccess {
            get {
                return ResourceManager.GetString("AppBarCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBarItem is added successfully.
        /// </summary>
        public static string AppBarItemAddedSuccess {
            get {
                return ResourceManager.GetString("AppBarItemAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBarItem is Removed successfully.
        /// </summary>
        public static string AppBarItemRemovedSuccess {
            get {
                return ResourceManager.GetString("AppBarItemRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBarMenuItem is added successfully.
        /// </summary>
        public static string AppBarMenuItemAddedSuccess {
            get {
                return ResourceManager.GetString("AppBarMenuItemAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBar MenuItem is Removed successfully.
        /// </summary>
        public static string AppBarMenuItemRemovedSuccess {
            get {
                return ResourceManager.GetString("AppBarMenuItemRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBar mode is changed.
        /// </summary>
        public static string AppBarModeChangedSuccess {
            get {
                return ResourceManager.GetString("AppBarModeChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBar visibility is changed.
        /// </summary>
        public static string AppBarvisibilityChangedSuccess {
            get {
                return ResourceManager.GetString("AppBarvisibilityChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact Added Successfully.
        /// </summary>
        public static string ContactAddedSuccesss {
            get {
                return ResourceManager.GetString("ContactAddedSuccesss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Successfully Written in the file.
        /// </summary>
        public static string ContentWrittenSuccess {
            get {
                return ResourceManager.GetString("ContentWrittenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items deleted.
        /// </summary>
        public static string DictionaryAllItemDeletedSuccess {
            get {
                return ResourceManager.GetString("DictionaryAllItemDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added successfully.
        /// </summary>
        public static string DictionaryItemAddedSuccess {
            get {
                return ResourceManager.GetString("DictionaryItemAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully removed.
        /// </summary>
        public static string DictionaryItemRemovedSuccess {
            get {
                return ResourceManager.GetString("DictionaryItemRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Created Successfully.
        /// </summary>
        public static string DirectoryCreatedSuccess {
            get {
                return ResourceManager.GetString("DirectoryCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Deleted Successfully.
        /// </summary>
        public static string DirectoryDeletedSuccess {
            get {
                return ResourceManager.GetString("DirectoryDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Created Successfully.
        /// </summary>
        public static string FileCreatedSuccess {
            get {
                return ResourceManager.GetString("FileCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Deleted Successfully.
        /// </summary>
        public static string FileDeletedSuccess {
            get {
                return ResourceManager.GetString("FileDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saved.
        /// </summary>
        public static string FileSavedSuccess {
            get {
                return ResourceManager.GetString("FileSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        //public static string OrubaseSuccessResultsStrings {
        //    get {
        //        return ResourceManager.GetString("OrubaseSuccessResultsStrings", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.18033
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace DemoApp.Resources {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-typ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrubaseSuccessResultsStrings_Designer {
            get {
                return ResourceManager.GetString("OrubaseSuccessResultsStrings_Designer", resourceCulture);
            }
        }
    }
}
